language: node_js
sudo: required
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
env:
  global:
    - secure: "CLwwxZxD/hrpGsSebO1Gd5i+fXwGvHFRPUkhCdKj8Y1VzCqNOdjOI0r1lFcIrzxD6+pCgfiUoJH+AtNaqBURsOmA7Ii+Nr7BNmtpfwNlhEqqxQPfcjJShFqn87u3HSU+NmGu3fgjpuO2Rvej8Iu2JEYFOy8EwkfvxXzNjBe5awOVqZi1X4izBEK7Ylom6MsGzG0V+4RXJAIv+1rHRRj+Q1Y/R9cRSiVmUaGDVmq6+lfjpDs3WtjpI88OiDspRbDMj2MHICbhqRruMVQccMJEylLSRJ0vCCTe9lRJMT4YXoaf/v3Nw1JTsq7PXqXnwZpMvGpOMvnJQLwBYzWRwbqRWNBM9eg4KzeBXDx1rg+8o1ECyWIMp2AdKYXQwSmalda0XNUWK3dVGjGJLvKq60958WsEBQKfYWvwF3Y9yKx8BiuF/hfDjPllorso+TqKxZnWNvEM+7ArL1skz2Tba0ZUzrlWNddBYSnvu3qbpHRhVXpSJDISOyp5kYCYr/8hnJnWTfV+/DOjObNopl7ZlfrbkxC38dw1nMg8XnSFqL28rZ/FoSlYEvir6A9NNw7e9qOBbHYUluJ+M3YxsItNpGAQrfoEXSU864bTdrwm9c843Q1t+GkAtGeCqeLlJ2u3oVw3ZudzEEZCT13SqJiYJdSunKrpUIlR1GkPMPHRS1T97IA="
    - secure: "KKA0zECOY+AQLDONfcYp3JJFLzHssnR4pc4vcaLBJ+GzE5HgqBZu2u7D8I659mFqnj9tiC2vF6MjrqTwP8QFqf8Nw+/AE7K/dUi9GNnvUhxpiAFgu48uArVAKhmKgs23PA2GxE0kZuhA3E81ivgn91oyN/3k3fAXc053mL0HJlnDj9H6RHoa2UgIC6JHRTjiJ/H1N1alTCVETutPTpgMCC3auWgGtlWDUN36GCqsu1QbmKMAJcB9L7TvsB+TGpsvNA2QY0o/xJMs/+Y/KT5m0Znngd6fD/8mydZaNEsLF4KyPy9MaHYd9K7n083PrI+v0aKGLHXi5CiIQmVWpIlSQAHM485ClO4mUqMNHpv3fzZ51svHiUu2wpENL2FOw4BifpIVzh4l/tbfto6T1lOsVMkNiBmIlj4VNp0ZPGIhXovmAXx6i7gJO4vZ/TvHpbRa2PfWM2NwXpTpeuX9ak2eweQ0Ujp0bR2qHhxf9cNTfec63+6YyxwAOo8fV/CwLWvjlCq0mkwbTwQEsl1cUl2TTZGHGTkJ5C3aDeV/ax4br7EvcEj6prDoSgpuwlC8JjoSFvKlS45Ut81c5mLkYqN87tqgJL7QFuPk+R+iqQK2tZsyRMUJ+bdIVQ3j2L5Wq1Se+DtmhduMPoFLW9O+RSbQnDQINJDagd7KtdBT+OpJVhM="
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - true || xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then true || polymer test -s
    'default'; fi
dist: trusty
